<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\SubCategory;
use App\Models\Unit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = array(
            array('id' => '1','name' => 'Fruit Trees SubCategory 1 Product 1','category_id' => '1','sub_category_id' => '1','unit_id' => '1','code' => 'PRD6762B7520AFCB','model' => 'Model 1','stock_amount' => '14','regular_price' => '688','selling_price' => '456','short_description' => 'Short description for Fruit Trees SubCategory 1 Product 1.','long_description' => 'Detailed description of Fruit Trees SubCategory 1 Product 1.','image' => 'images/products/fruit_trees_subcategory_1_product_1.jpg','hit_count' => '44','sales_count' => '11','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '2','name' => 'Fruit Trees SubCategory 1 Product 2','category_id' => '1','sub_category_id' => '1','unit_id' => '1','code' => 'PRD6762B7520C02F','model' => 'Model 2','stock_amount' => '36','regular_price' => '684','selling_price' => '465','short_description' => 'Short description for Fruit Trees SubCategory 1 Product 2.','long_description' => 'Detailed description of Fruit Trees SubCategory 1 Product 2.','image' => 'images/products/fruit_trees_subcategory_1_product_2.jpg','hit_count' => '1','sales_count' => '18','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '3','name' => 'Fruit Trees SubCategory 1 Product 3','category_id' => '1','sub_category_id' => '1','unit_id' => '1','code' => 'PRD6762B7520C860','model' => 'Model 3','stock_amount' => '61','regular_price' => '895','selling_price' => '551','short_description' => 'Short description for Fruit Trees SubCategory 1 Product 3.','long_description' => 'Detailed description of Fruit Trees SubCategory 1 Product 3.','image' => 'images/products/fruit_trees_subcategory_1_product_3.jpg','hit_count' => '20','sales_count' => '21','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '4','name' => 'Fruit Trees SubCategory 1 Product 4','category_id' => '1','sub_category_id' => '1','unit_id' => '1','code' => 'PRD6762B7520D049','model' => 'Model 4','stock_amount' => '28','regular_price' => '764','selling_price' => '574','short_description' => 'Short description for Fruit Trees SubCategory 1 Product 4.','long_description' => 'Detailed description of Fruit Trees SubCategory 1 Product 4.','image' => 'images/products/fruit_trees_subcategory_1_product_4.jpg','hit_count' => '23','sales_count' => '21','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '5','name' => 'Fruit Trees SubCategory 1 Product 5','category_id' => '1','sub_category_id' => '1','unit_id' => '1','code' => 'PRD6762B7520D706','model' => 'Model 5','stock_amount' => '36','regular_price' => '753','selling_price' => '704','short_description' => 'Short description for Fruit Trees SubCategory 1 Product 5.','long_description' => 'Detailed description of Fruit Trees SubCategory 1 Product 5.','image' => 'images/products/fruit_trees_subcategory_1_product_5.jpg','hit_count' => '15','sales_count' => '16','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '6','name' => 'Fruit Trees SubCategory 2 Product 1','category_id' => '1','sub_category_id' => '2','unit_id' => '1','code' => 'PRD6762B7520E169','model' => 'Model 1','stock_amount' => '81','regular_price' => '775','selling_price' => '555','short_description' => 'Short description for Fruit Trees SubCategory 2 Product 1.','long_description' => 'Detailed description of Fruit Trees SubCategory 2 Product 1.','image' => 'images/products/fruit_trees_subcategory_2_product_1.jpg','hit_count' => '16','sales_count' => '1','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '7','name' => 'Fruit Trees SubCategory 2 Product 2','category_id' => '1','sub_category_id' => '2','unit_id' => '1','code' => 'PRD6762B7520EDAA','model' => 'Model 2','stock_amount' => '88','regular_price' => '768','selling_price' => '474','short_description' => 'Short description for Fruit Trees SubCategory 2 Product 2.','long_description' => 'Detailed description of Fruit Trees SubCategory 2 Product 2.','image' => 'images/products/fruit_trees_subcategory_2_product_2.jpg','hit_count' => '10','sales_count' => '14','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '8','name' => 'Fruit Trees SubCategory 2 Product 3','category_id' => '1','sub_category_id' => '2','unit_id' => '1','code' => 'PRD6762B7520F639','model' => 'Model 3','stock_amount' => '58','regular_price' => '679','selling_price' => '441','short_description' => 'Short description for Fruit Trees SubCategory 2 Product 3.','long_description' => 'Detailed description of Fruit Trees SubCategory 2 Product 3.','image' => 'images/products/fruit_trees_subcategory_2_product_3.jpg','hit_count' => '50','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '9','name' => 'Fruit Trees SubCategory 2 Product 4','category_id' => '1','sub_category_id' => '2','unit_id' => '1','code' => 'PRD6762B7520FED3','model' => 'Model 4','stock_amount' => '15','regular_price' => '761','selling_price' => '729','short_description' => 'Short description for Fruit Trees SubCategory 2 Product 4.','long_description' => 'Detailed description of Fruit Trees SubCategory 2 Product 4.','image' => 'images/products/fruit_trees_subcategory_2_product_4.jpg','hit_count' => '5','sales_count' => '0','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '10','name' => 'Fruit Trees SubCategory 2 Product 5','category_id' => '1','sub_category_id' => '2','unit_id' => '1','code' => 'PRD6762B75210543','model' => 'Model 5','stock_amount' => '68','regular_price' => '732','selling_price' => '796','short_description' => 'Short description for Fruit Trees SubCategory 2 Product 5.','long_description' => 'Detailed description of Fruit Trees SubCategory 2 Product 5.','image' => 'images/products/fruit_trees_subcategory_2_product_5.jpg','hit_count' => '2','sales_count' => '10','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '11','name' => 'Fruit Trees SubCategory 3 Product 1','category_id' => '1','sub_category_id' => '3','unit_id' => '1','code' => 'PRD6762B75210DEF','model' => 'Model 1','stock_amount' => '48','regular_price' => '905','selling_price' => '786','short_description' => 'Short description for Fruit Trees SubCategory 3 Product 1.','long_description' => 'Detailed description of Fruit Trees SubCategory 3 Product 1.','image' => 'images/products/fruit_trees_subcategory_3_product_1.jpg','hit_count' => '37','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '12','name' => 'Fruit Trees SubCategory 3 Product 2','category_id' => '1','sub_category_id' => '3','unit_id' => '1','code' => 'PRD6762B752115D1','model' => 'Model 2','stock_amount' => '63','regular_price' => '754','selling_price' => '499','short_description' => 'Short description for Fruit Trees SubCategory 3 Product 2.','long_description' => 'Detailed description of Fruit Trees SubCategory 3 Product 2.','image' => 'images/products/fruit_trees_subcategory_3_product_2.jpg','hit_count' => '4','sales_count' => '18','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '13','name' => 'Fruit Trees SubCategory 3 Product 3','category_id' => '1','sub_category_id' => '3','unit_id' => '1','code' => 'PRD6762B75211F11','model' => 'Model 3','stock_amount' => '81','regular_price' => '530','selling_price' => '492','short_description' => 'Short description for Fruit Trees SubCategory 3 Product 3.','long_description' => 'Detailed description of Fruit Trees SubCategory 3 Product 3.','image' => 'images/products/fruit_trees_subcategory_3_product_3.jpg','hit_count' => '15','sales_count' => '28','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '14','name' => 'Fruit Trees SubCategory 3 Product 4','category_id' => '1','sub_category_id' => '3','unit_id' => '1','code' => 'PRD6762B75212A67','model' => 'Model 4','stock_amount' => '15','regular_price' => '839','selling_price' => '708','short_description' => 'Short description for Fruit Trees SubCategory 3 Product 4.','long_description' => 'Detailed description of Fruit Trees SubCategory 3 Product 4.','image' => 'images/products/fruit_trees_subcategory_3_product_4.jpg','hit_count' => '48','sales_count' => '29','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '15','name' => 'Fruit Trees SubCategory 3 Product 5','category_id' => '1','sub_category_id' => '3','unit_id' => '1','code' => 'PRD6762B752131A4','model' => 'Model 5','stock_amount' => '42','regular_price' => '716','selling_price' => '485','short_description' => 'Short description for Fruit Trees SubCategory 3 Product 5.','long_description' => 'Detailed description of Fruit Trees SubCategory 3 Product 5.','image' => 'images/products/fruit_trees_subcategory_3_product_5.jpg','hit_count' => '36','sales_count' => '4','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '16','name' => 'Flowering Trees SubCategory 1 Product 1','category_id' => '2','sub_category_id' => '4','unit_id' => '1','code' => 'PRD6762B75213835','model' => 'Model 1','stock_amount' => '61','regular_price' => '661','selling_price' => '509','short_description' => 'Short description for Flowering Trees SubCategory 1 Product 1.','long_description' => 'Detailed description of Flowering Trees SubCategory 1 Product 1.','image' => 'images/products/flowering_trees_subcategory_1_product_1.jpg','hit_count' => '2','sales_count' => '7','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '17','name' => 'Flowering Trees SubCategory 1 Product 2','category_id' => '2','sub_category_id' => '4','unit_id' => '1','code' => 'PRD6762B75214014','model' => 'Model 2','stock_amount' => '30','regular_price' => '789','selling_price' => '739','short_description' => 'Short description for Flowering Trees SubCategory 1 Product 2.','long_description' => 'Detailed description of Flowering Trees SubCategory 1 Product 2.','image' => 'images/products/flowering_trees_subcategory_1_product_2.jpg','hit_count' => '9','sales_count' => '7','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '18','name' => 'Flowering Trees SubCategory 1 Product 3','category_id' => '2','sub_category_id' => '4','unit_id' => '1','code' => 'PRD6762B752147C0','model' => 'Model 3','stock_amount' => '99','regular_price' => '956','selling_price' => '574','short_description' => 'Short description for Flowering Trees SubCategory 1 Product 3.','long_description' => 'Detailed description of Flowering Trees SubCategory 1 Product 3.','image' => 'images/products/flowering_trees_subcategory_1_product_3.jpg','hit_count' => '50','sales_count' => '4','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '19','name' => 'Flowering Trees SubCategory 1 Product 4','category_id' => '2','sub_category_id' => '4','unit_id' => '1','code' => 'PRD6762B75214FC5','model' => 'Model 4','stock_amount' => '38','regular_price' => '864','selling_price' => '526','short_description' => 'Short description for Flowering Trees SubCategory 1 Product 4.','long_description' => 'Detailed description of Flowering Trees SubCategory 1 Product 4.','image' => 'images/products/flowering_trees_subcategory_1_product_4.jpg','hit_count' => '46','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '20','name' => 'Flowering Trees SubCategory 1 Product 5','category_id' => '2','sub_category_id' => '4','unit_id' => '1','code' => 'PRD6762B752157BF','model' => 'Model 5','stock_amount' => '22','regular_price' => '830','selling_price' => '580','short_description' => 'Short description for Flowering Trees SubCategory 1 Product 5.','long_description' => 'Detailed description of Flowering Trees SubCategory 1 Product 5.','image' => 'images/products/flowering_trees_subcategory_1_product_5.jpg','hit_count' => '3','sales_count' => '29','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '21','name' => 'Flowering Trees SubCategory 2 Product 1','category_id' => '2','sub_category_id' => '5','unit_id' => '1','code' => 'PRD6762B75216128','model' => 'Model 1','stock_amount' => '17','regular_price' => '609','selling_price' => '816','short_description' => 'Short description for Flowering Trees SubCategory 2 Product 1.','long_description' => 'Detailed description of Flowering Trees SubCategory 2 Product 1.','image' => 'images/products/flowering_trees_subcategory_2_product_1.jpg','hit_count' => '37','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '22','name' => 'Flowering Trees SubCategory 2 Product 2','category_id' => '2','sub_category_id' => '5','unit_id' => '1','code' => 'PRD6762B75216D8C','model' => 'Model 2','stock_amount' => '12','regular_price' => '826','selling_price' => '554','short_description' => 'Short description for Flowering Trees SubCategory 2 Product 2.','long_description' => 'Detailed description of Flowering Trees SubCategory 2 Product 2.','image' => 'images/products/flowering_trees_subcategory_2_product_2.jpg','hit_count' => '8','sales_count' => '19','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '23','name' => 'Flowering Trees SubCategory 2 Product 3','category_id' => '2','sub_category_id' => '5','unit_id' => '1','code' => 'PRD6762B75217641','model' => 'Model 3','stock_amount' => '20','regular_price' => '748','selling_price' => '636','short_description' => 'Short description for Flowering Trees SubCategory 2 Product 3.','long_description' => 'Detailed description of Flowering Trees SubCategory 2 Product 3.','image' => 'images/products/flowering_trees_subcategory_2_product_3.jpg','hit_count' => '33','sales_count' => '13','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '24','name' => 'Flowering Trees SubCategory 2 Product 4','category_id' => '2','sub_category_id' => '5','unit_id' => '1','code' => 'PRD6762B75217E32','model' => 'Model 4','stock_amount' => '17','regular_price' => '726','selling_price' => '464','short_description' => 'Short description for Flowering Trees SubCategory 2 Product 4.','long_description' => 'Detailed description of Flowering Trees SubCategory 2 Product 4.','image' => 'images/products/flowering_trees_subcategory_2_product_4.jpg','hit_count' => '2','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '25','name' => 'Flowering Trees SubCategory 2 Product 5','category_id' => '2','sub_category_id' => '5','unit_id' => '1','code' => 'PRD6762B75218519','model' => 'Model 5','stock_amount' => '86','regular_price' => '970','selling_price' => '729','short_description' => 'Short description for Flowering Trees SubCategory 2 Product 5.','long_description' => 'Detailed description of Flowering Trees SubCategory 2 Product 5.','image' => 'images/products/flowering_trees_subcategory_2_product_5.jpg','hit_count' => '8','sales_count' => '5','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '26','name' => 'Flowering Trees SubCategory 3 Product 1','category_id' => '2','sub_category_id' => '6','unit_id' => '1','code' => 'PRD6762B75218B80','model' => 'Model 1','stock_amount' => '76','regular_price' => '566','selling_price' => '764','short_description' => 'Short description for Flowering Trees SubCategory 3 Product 1.','long_description' => 'Detailed description of Flowering Trees SubCategory 3 Product 1.','image' => 'images/products/flowering_trees_subcategory_3_product_1.jpg','hit_count' => '7','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '27','name' => 'Flowering Trees SubCategory 3 Product 2','category_id' => '2','sub_category_id' => '6','unit_id' => '1','code' => 'PRD6762B75219248','model' => 'Model 2','stock_amount' => '81','regular_price' => '572','selling_price' => '879','short_description' => 'Short description for Flowering Trees SubCategory 3 Product 2.','long_description' => 'Detailed description of Flowering Trees SubCategory 3 Product 2.','image' => 'images/products/flowering_trees_subcategory_3_product_2.jpg','hit_count' => '33','sales_count' => '15','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '28','name' => 'Flowering Trees SubCategory 3 Product 3','category_id' => '2','sub_category_id' => '6','unit_id' => '1','code' => 'PRD6762B752198C6','model' => 'Model 3','stock_amount' => '31','regular_price' => '526','selling_price' => '899','short_description' => 'Short description for Flowering Trees SubCategory 3 Product 3.','long_description' => 'Detailed description of Flowering Trees SubCategory 3 Product 3.','image' => 'images/products/flowering_trees_subcategory_3_product_3.jpg','hit_count' => '28','sales_count' => '17','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '29','name' => 'Flowering Trees SubCategory 3 Product 4','category_id' => '2','sub_category_id' => '6','unit_id' => '1','code' => 'PRD6762B7521A260','model' => 'Model 4','stock_amount' => '72','regular_price' => '910','selling_price' => '525','short_description' => 'Short description for Flowering Trees SubCategory 3 Product 4.','long_description' => 'Detailed description of Flowering Trees SubCategory 3 Product 4.','image' => 'images/products/flowering_trees_subcategory_3_product_4.jpg','hit_count' => '3','sales_count' => '19','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '30','name' => 'Flowering Trees SubCategory 3 Product 5','category_id' => '2','sub_category_id' => '6','unit_id' => '1','code' => 'PRD6762B7521A9B1','model' => 'Model 5','stock_amount' => '17','regular_price' => '746','selling_price' => '874','short_description' => 'Short description for Flowering Trees SubCategory 3 Product 5.','long_description' => 'Detailed description of Flowering Trees SubCategory 3 Product 5.','image' => 'images/products/flowering_trees_subcategory_3_product_5.jpg','hit_count' => '30','sales_count' => '29','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '31','name' => 'Shade Trees SubCategory 1 Product 1','category_id' => '3','sub_category_id' => '7','unit_id' => '1','code' => 'PRD6762B7521B064','model' => 'Model 1','stock_amount' => '16','regular_price' => '727','selling_price' => '443','short_description' => 'Short description for Shade Trees SubCategory 1 Product 1.','long_description' => 'Detailed description of Shade Trees SubCategory 1 Product 1.','image' => 'images/products/shade_trees_subcategory_1_product_1.jpg','hit_count' => '45','sales_count' => '0','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '32','name' => 'Shade Trees SubCategory 1 Product 2','category_id' => '3','sub_category_id' => '7','unit_id' => '1','code' => 'PRD6762B7521B6B2','model' => 'Model 2','stock_amount' => '44','regular_price' => '514','selling_price' => '841','short_description' => 'Short description for Shade Trees SubCategory 1 Product 2.','long_description' => 'Detailed description of Shade Trees SubCategory 1 Product 2.','image' => 'images/products/shade_trees_subcategory_1_product_2.jpg','hit_count' => '4','sales_count' => '11','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '33','name' => 'Shade Trees SubCategory 1 Product 3','category_id' => '3','sub_category_id' => '7','unit_id' => '1','code' => 'PRD6762B7521BD4F','model' => 'Model 3','stock_amount' => '75','regular_price' => '818','selling_price' => '796','short_description' => 'Short description for Shade Trees SubCategory 1 Product 3.','long_description' => 'Detailed description of Shade Trees SubCategory 1 Product 3.','image' => 'images/products/shade_trees_subcategory_1_product_3.jpg','hit_count' => '0','sales_count' => '23','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '34','name' => 'Shade Trees SubCategory 1 Product 4','category_id' => '3','sub_category_id' => '7','unit_id' => '1','code' => 'PRD6762B7521C490','model' => 'Model 4','stock_amount' => '33','regular_price' => '984','selling_price' => '630','short_description' => 'Short description for Shade Trees SubCategory 1 Product 4.','long_description' => 'Detailed description of Shade Trees SubCategory 1 Product 4.','image' => 'images/products/shade_trees_subcategory_1_product_4.jpg','hit_count' => '10','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '35','name' => 'Shade Trees SubCategory 1 Product 5','category_id' => '3','sub_category_id' => '7','unit_id' => '1','code' => 'PRD6762B7521CB3C','model' => 'Model 5','stock_amount' => '15','regular_price' => '712','selling_price' => '685','short_description' => 'Short description for Shade Trees SubCategory 1 Product 5.','long_description' => 'Detailed description of Shade Trees SubCategory 1 Product 5.','image' => 'images/products/shade_trees_subcategory_1_product_5.jpg','hit_count' => '7','sales_count' => '29','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '36','name' => 'Shade Trees SubCategory 2 Product 1','category_id' => '3','sub_category_id' => '8','unit_id' => '1','code' => 'PRD6762B7521D15D','model' => 'Model 1','stock_amount' => '84','regular_price' => '821','selling_price' => '631','short_description' => 'Short description for Shade Trees SubCategory 2 Product 1.','long_description' => 'Detailed description of Shade Trees SubCategory 2 Product 1.','image' => 'images/products/shade_trees_subcategory_2_product_1.jpg','hit_count' => '5','sales_count' => '22','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '37','name' => 'Shade Trees SubCategory 2 Product 2','category_id' => '3','sub_category_id' => '8','unit_id' => '1','code' => 'PRD6762B7521D85D','model' => 'Model 2','stock_amount' => '70','regular_price' => '818','selling_price' => '600','short_description' => 'Short description for Shade Trees SubCategory 2 Product 2.','long_description' => 'Detailed description of Shade Trees SubCategory 2 Product 2.','image' => 'images/products/shade_trees_subcategory_2_product_2.jpg','hit_count' => '41','sales_count' => '2','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '38','name' => 'Shade Trees SubCategory 2 Product 3','category_id' => '3','sub_category_id' => '8','unit_id' => '1','code' => 'PRD6762B7521E06B','model' => 'Model 3','stock_amount' => '70','regular_price' => '690','selling_price' => '660','short_description' => 'Short description for Shade Trees SubCategory 2 Product 3.','long_description' => 'Detailed description of Shade Trees SubCategory 2 Product 3.','image' => 'images/products/shade_trees_subcategory_2_product_3.jpg','hit_count' => '31','sales_count' => '7','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '39','name' => 'Shade Trees SubCategory 2 Product 4','category_id' => '3','sub_category_id' => '8','unit_id' => '1','code' => 'PRD6762B7521E77C','model' => 'Model 4','stock_amount' => '24','regular_price' => '760','selling_price' => '526','short_description' => 'Short description for Shade Trees SubCategory 2 Product 4.','long_description' => 'Detailed description of Shade Trees SubCategory 2 Product 4.','image' => 'images/products/shade_trees_subcategory_2_product_4.jpg','hit_count' => '5','sales_count' => '18','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '40','name' => 'Shade Trees SubCategory 2 Product 5','category_id' => '3','sub_category_id' => '8','unit_id' => '1','code' => 'PRD6762B7521EE23','model' => 'Model 5','stock_amount' => '61','regular_price' => '837','selling_price' => '511','short_description' => 'Short description for Shade Trees SubCategory 2 Product 5.','long_description' => 'Detailed description of Shade Trees SubCategory 2 Product 5.','image' => 'images/products/shade_trees_subcategory_2_product_5.jpg','hit_count' => '44','sales_count' => '21','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '41','name' => 'Shade Trees SubCategory 3 Product 1','category_id' => '3','sub_category_id' => '9','unit_id' => '1','code' => 'PRD6762B7521F4DF','model' => 'Model 1','stock_amount' => '52','regular_price' => '617','selling_price' => '502','short_description' => 'Short description for Shade Trees SubCategory 3 Product 1.','long_description' => 'Detailed description of Shade Trees SubCategory 3 Product 1.','image' => 'images/products/shade_trees_subcategory_3_product_1.jpg','hit_count' => '33','sales_count' => '27','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '42','name' => 'Shade Trees SubCategory 3 Product 2','category_id' => '3','sub_category_id' => '9','unit_id' => '1','code' => 'PRD6762B7521FB99','model' => 'Model 2','stock_amount' => '40','regular_price' => '764','selling_price' => '459','short_description' => 'Short description for Shade Trees SubCategory 3 Product 2.','long_description' => 'Detailed description of Shade Trees SubCategory 3 Product 2.','image' => 'images/products/shade_trees_subcategory_3_product_2.jpg','hit_count' => '26','sales_count' => '13','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '43','name' => 'Shade Trees SubCategory 3 Product 3','category_id' => '3','sub_category_id' => '9','unit_id' => '1','code' => 'PRD6762B75220218','model' => 'Model 3','stock_amount' => '56','regular_price' => '987','selling_price' => '681','short_description' => 'Short description for Shade Trees SubCategory 3 Product 3.','long_description' => 'Detailed description of Shade Trees SubCategory 3 Product 3.','image' => 'images/products/shade_trees_subcategory_3_product_3.jpg','hit_count' => '36','sales_count' => '20','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '44','name' => 'Shade Trees SubCategory 3 Product 4','category_id' => '3','sub_category_id' => '9','unit_id' => '1','code' => 'PRD6762B752208A3','model' => 'Model 4','stock_amount' => '74','regular_price' => '959','selling_price' => '610','short_description' => 'Short description for Shade Trees SubCategory 3 Product 4.','long_description' => 'Detailed description of Shade Trees SubCategory 3 Product 4.','image' => 'images/products/shade_trees_subcategory_3_product_4.jpg','hit_count' => '22','sales_count' => '24','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '45','name' => 'Shade Trees SubCategory 3 Product 5','category_id' => '3','sub_category_id' => '9','unit_id' => '1','code' => 'PRD6762B75220F53','model' => 'Model 5','stock_amount' => '99','regular_price' => '629','selling_price' => '443','short_description' => 'Short description for Shade Trees SubCategory 3 Product 5.','long_description' => 'Detailed description of Shade Trees SubCategory 3 Product 5.','image' => 'images/products/shade_trees_subcategory_3_product_5.jpg','hit_count' => '39','sales_count' => '17','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '46','name' => 'Evergreen Trees SubCategory 1 Product 1','category_id' => '4','sub_category_id' => '10','unit_id' => '1','code' => 'PRD6762B752215D4','model' => 'Model 1','stock_amount' => '31','regular_price' => '747','selling_price' => '634','short_description' => 'Short description for Evergreen Trees SubCategory 1 Product 1.','long_description' => 'Detailed description of Evergreen Trees SubCategory 1 Product 1.','image' => 'images/products/evergreen_trees_subcategory_1_product_1.jpg','hit_count' => '49','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '47','name' => 'Evergreen Trees SubCategory 1 Product 2','category_id' => '4','sub_category_id' => '10','unit_id' => '1','code' => 'PRD6762B75221C8E','model' => 'Model 2','stock_amount' => '83','regular_price' => '955','selling_price' => '865','short_description' => 'Short description for Evergreen Trees SubCategory 1 Product 2.','long_description' => 'Detailed description of Evergreen Trees SubCategory 1 Product 2.','image' => 'images/products/evergreen_trees_subcategory_1_product_2.jpg','hit_count' => '38','sales_count' => '12','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '48','name' => 'Evergreen Trees SubCategory 1 Product 3','category_id' => '4','sub_category_id' => '10','unit_id' => '1','code' => 'PRD6762B75222317','model' => 'Model 3','stock_amount' => '43','regular_price' => '872','selling_price' => '780','short_description' => 'Short description for Evergreen Trees SubCategory 1 Product 3.','long_description' => 'Detailed description of Evergreen Trees SubCategory 1 Product 3.','image' => 'images/products/evergreen_trees_subcategory_1_product_3.jpg','hit_count' => '4','sales_count' => '13','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '49','name' => 'Evergreen Trees SubCategory 1 Product 4','category_id' => '4','sub_category_id' => '10','unit_id' => '1','code' => 'PRD6762B75222E08','model' => 'Model 4','stock_amount' => '82','regular_price' => '879','selling_price' => '803','short_description' => 'Short description for Evergreen Trees SubCategory 1 Product 4.','long_description' => 'Detailed description of Evergreen Trees SubCategory 1 Product 4.','image' => 'images/products/evergreen_trees_subcategory_1_product_4.jpg','hit_count' => '28','sales_count' => '26','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '50','name' => 'Evergreen Trees SubCategory 1 Product 5','category_id' => '4','sub_category_id' => '10','unit_id' => '1','code' => 'PRD6762B75223499','model' => 'Model 5','stock_amount' => '10','regular_price' => '533','selling_price' => '794','short_description' => 'Short description for Evergreen Trees SubCategory 1 Product 5.','long_description' => 'Detailed description of Evergreen Trees SubCategory 1 Product 5.','image' => 'images/products/evergreen_trees_subcategory_1_product_5.jpg','hit_count' => '30','sales_count' => '1','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '51','name' => 'Evergreen Trees SubCategory 2 Product 1','category_id' => '4','sub_category_id' => '11','unit_id' => '1','code' => 'PRD6762B75223D5A','model' => 'Model 1','stock_amount' => '79','regular_price' => '896','selling_price' => '522','short_description' => 'Short description for Evergreen Trees SubCategory 2 Product 1.','long_description' => 'Detailed description of Evergreen Trees SubCategory 2 Product 1.','image' => 'images/products/evergreen_trees_subcategory_2_product_1.jpg','hit_count' => '37','sales_count' => '27','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '52','name' => 'Evergreen Trees SubCategory 2 Product 2','category_id' => '4','sub_category_id' => '11','unit_id' => '1','code' => 'PRD6762B7522440D','model' => 'Model 2','stock_amount' => '73','regular_price' => '919','selling_price' => '731','short_description' => 'Short description for Evergreen Trees SubCategory 2 Product 2.','long_description' => 'Detailed description of Evergreen Trees SubCategory 2 Product 2.','image' => 'images/products/evergreen_trees_subcategory_2_product_2.jpg','hit_count' => '9','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '53','name' => 'Evergreen Trees SubCategory 2 Product 3','category_id' => '4','sub_category_id' => '11','unit_id' => '1','code' => 'PRD6762B75224AD9','model' => 'Model 3','stock_amount' => '57','regular_price' => '590','selling_price' => '837','short_description' => 'Short description for Evergreen Trees SubCategory 2 Product 3.','long_description' => 'Detailed description of Evergreen Trees SubCategory 2 Product 3.','image' => 'images/products/evergreen_trees_subcategory_2_product_3.jpg','hit_count' => '7','sales_count' => '1','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '54','name' => 'Evergreen Trees SubCategory 2 Product 4','category_id' => '4','sub_category_id' => '11','unit_id' => '1','code' => 'PRD6762B75225160','model' => 'Model 4','stock_amount' => '17','regular_price' => '644','selling_price' => '520','short_description' => 'Short description for Evergreen Trees SubCategory 2 Product 4.','long_description' => 'Detailed description of Evergreen Trees SubCategory 2 Product 4.','image' => 'images/products/evergreen_trees_subcategory_2_product_4.jpg','hit_count' => '13','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '55','name' => 'Evergreen Trees SubCategory 2 Product 5','category_id' => '4','sub_category_id' => '11','unit_id' => '1','code' => 'PRD6762B75225749','model' => 'Model 5','stock_amount' => '38','regular_price' => '560','selling_price' => '499','short_description' => 'Short description for Evergreen Trees SubCategory 2 Product 5.','long_description' => 'Detailed description of Evergreen Trees SubCategory 2 Product 5.','image' => 'images/products/evergreen_trees_subcategory_2_product_5.jpg','hit_count' => '0','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '56','name' => 'Evergreen Trees SubCategory 3 Product 1','category_id' => '4','sub_category_id' => '12','unit_id' => '1','code' => 'PRD6762B75225F85','model' => 'Model 1','stock_amount' => '29','regular_price' => '751','selling_price' => '838','short_description' => 'Short description for Evergreen Trees SubCategory 3 Product 1.','long_description' => 'Detailed description of Evergreen Trees SubCategory 3 Product 1.','image' => 'images/products/evergreen_trees_subcategory_3_product_1.jpg','hit_count' => '10','sales_count' => '17','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '57','name' => 'Evergreen Trees SubCategory 3 Product 2','category_id' => '4','sub_category_id' => '12','unit_id' => '1','code' => 'PRD6762B752266F3','model' => 'Model 2','stock_amount' => '45','regular_price' => '527','selling_price' => '479','short_description' => 'Short description for Evergreen Trees SubCategory 3 Product 2.','long_description' => 'Detailed description of Evergreen Trees SubCategory 3 Product 2.','image' => 'images/products/evergreen_trees_subcategory_3_product_2.jpg','hit_count' => '7','sales_count' => '0','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '58','name' => 'Evergreen Trees SubCategory 3 Product 3','category_id' => '4','sub_category_id' => '12','unit_id' => '1','code' => 'PRD6762B75226D94','model' => 'Model 3','stock_amount' => '29','regular_price' => '909','selling_price' => '567','short_description' => 'Short description for Evergreen Trees SubCategory 3 Product 3.','long_description' => 'Detailed description of Evergreen Trees SubCategory 3 Product 3.','image' => 'images/products/evergreen_trees_subcategory_3_product_3.jpg','hit_count' => '32','sales_count' => '21','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '59','name' => 'Evergreen Trees SubCategory 3 Product 4','category_id' => '4','sub_category_id' => '12','unit_id' => '1','code' => 'PRD6762B7522743C','model' => 'Model 4','stock_amount' => '55','regular_price' => '842','selling_price' => '521','short_description' => 'Short description for Evergreen Trees SubCategory 3 Product 4.','long_description' => 'Detailed description of Evergreen Trees SubCategory 3 Product 4.','image' => 'images/products/evergreen_trees_subcategory_3_product_4.jpg','hit_count' => '29','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '60','name' => 'Evergreen Trees SubCategory 3 Product 5','category_id' => '4','sub_category_id' => '12','unit_id' => '1','code' => 'PRD6762B75227ACC','model' => 'Model 5','stock_amount' => '71','regular_price' => '601','selling_price' => '849','short_description' => 'Short description for Evergreen Trees SubCategory 3 Product 5.','long_description' => 'Detailed description of Evergreen Trees SubCategory 3 Product 5.','image' => 'images/products/evergreen_trees_subcategory_3_product_5.jpg','hit_count' => '14','sales_count' => '15','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '61','name' => 'Deciduous Trees SubCategory 1 Product 1','category_id' => '5','sub_category_id' => '13','unit_id' => '1','code' => 'PRD6762B75228174','model' => 'Model 1','stock_amount' => '27','regular_price' => '948','selling_price' => '633','short_description' => 'Short description for Deciduous Trees SubCategory 1 Product 1.','long_description' => 'Detailed description of Deciduous Trees SubCategory 1 Product 1.','image' => 'images/products/deciduous_trees_subcategory_1_product_1.jpg','hit_count' => '7','sales_count' => '3','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '62','name' => 'Deciduous Trees SubCategory 1 Product 2','category_id' => '5','sub_category_id' => '13','unit_id' => '1','code' => 'PRD6762B7522880B','model' => 'Model 2','stock_amount' => '81','regular_price' => '504','selling_price' => '416','short_description' => 'Short description for Deciduous Trees SubCategory 1 Product 2.','long_description' => 'Detailed description of Deciduous Trees SubCategory 1 Product 2.','image' => 'images/products/deciduous_trees_subcategory_1_product_2.jpg','hit_count' => '35','sales_count' => '5','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '63','name' => 'Deciduous Trees SubCategory 1 Product 3','category_id' => '5','sub_category_id' => '13','unit_id' => '1','code' => 'PRD6762B75228ECB','model' => 'Model 3','stock_amount' => '88','regular_price' => '570','selling_price' => '436','short_description' => 'Short description for Deciduous Trees SubCategory 1 Product 3.','long_description' => 'Detailed description of Deciduous Trees SubCategory 1 Product 3.','image' => 'images/products/deciduous_trees_subcategory_1_product_3.jpg','hit_count' => '37','sales_count' => '0','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '64','name' => 'Deciduous Trees SubCategory 1 Product 4','category_id' => '5','sub_category_id' => '13','unit_id' => '1','code' => 'PRD6762B75229530','model' => 'Model 4','stock_amount' => '85','regular_price' => '911','selling_price' => '487','short_description' => 'Short description for Deciduous Trees SubCategory 1 Product 4.','long_description' => 'Detailed description of Deciduous Trees SubCategory 1 Product 4.','image' => 'images/products/deciduous_trees_subcategory_1_product_4.jpg','hit_count' => '5','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '65','name' => 'Deciduous Trees SubCategory 1 Product 5','category_id' => '5','sub_category_id' => '13','unit_id' => '1','code' => 'PRD6762B75229BB9','model' => 'Model 5','stock_amount' => '93','regular_price' => '719','selling_price' => '528','short_description' => 'Short description for Deciduous Trees SubCategory 1 Product 5.','long_description' => 'Detailed description of Deciduous Trees SubCategory 1 Product 5.','image' => 'images/products/deciduous_trees_subcategory_1_product_5.jpg','hit_count' => '36','sales_count' => '8','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '66','name' => 'Deciduous Trees SubCategory 2 Product 1','category_id' => '5','sub_category_id' => '14','unit_id' => '1','code' => 'PRD6762B7522A21C','model' => 'Model 1','stock_amount' => '29','regular_price' => '812','selling_price' => '687','short_description' => 'Short description for Deciduous Trees SubCategory 2 Product 1.','long_description' => 'Detailed description of Deciduous Trees SubCategory 2 Product 1.','image' => 'images/products/deciduous_trees_subcategory_2_product_1.jpg','hit_count' => '16','sales_count' => '13','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '67','name' => 'Deciduous Trees SubCategory 2 Product 2','category_id' => '5','sub_category_id' => '14','unit_id' => '1','code' => 'PRD6762B7522A8DA','model' => 'Model 2','stock_amount' => '38','regular_price' => '889','selling_price' => '651','short_description' => 'Short description for Deciduous Trees SubCategory 2 Product 2.','long_description' => 'Detailed description of Deciduous Trees SubCategory 2 Product 2.','image' => 'images/products/deciduous_trees_subcategory_2_product_2.jpg','hit_count' => '19','sales_count' => '30','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '68','name' => 'Deciduous Trees SubCategory 2 Product 3','category_id' => '5','sub_category_id' => '14','unit_id' => '1','code' => 'PRD6762B7522AF59','model' => 'Model 3','stock_amount' => '25','regular_price' => '651','selling_price' => '631','short_description' => 'Short description for Deciduous Trees SubCategory 2 Product 3.','long_description' => 'Detailed description of Deciduous Trees SubCategory 2 Product 3.','image' => 'images/products/deciduous_trees_subcategory_2_product_3.jpg','hit_count' => '6','sales_count' => '2','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '69','name' => 'Deciduous Trees SubCategory 2 Product 4','category_id' => '5','sub_category_id' => '14','unit_id' => '1','code' => 'PRD6762B7522B636','model' => 'Model 4','stock_amount' => '57','regular_price' => '848','selling_price' => '524','short_description' => 'Short description for Deciduous Trees SubCategory 2 Product 4.','long_description' => 'Detailed description of Deciduous Trees SubCategory 2 Product 4.','image' => 'images/products/deciduous_trees_subcategory_2_product_4.jpg','hit_count' => '50','sales_count' => '16','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '70','name' => 'Deciduous Trees SubCategory 2 Product 5','category_id' => '5','sub_category_id' => '14','unit_id' => '1','code' => 'PRD6762B7522BCA2','model' => 'Model 5','stock_amount' => '96','regular_price' => '742','selling_price' => '728','short_description' => 'Short description for Deciduous Trees SubCategory 2 Product 5.','long_description' => 'Detailed description of Deciduous Trees SubCategory 2 Product 5.','image' => 'images/products/deciduous_trees_subcategory_2_product_5.jpg','hit_count' => '19','sales_count' => '16','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '71','name' => 'Deciduous Trees SubCategory 3 Product 1','category_id' => '5','sub_category_id' => '15','unit_id' => '1','code' => 'PRD6762B7522C7A1','model' => 'Model 1','stock_amount' => '14','regular_price' => '713','selling_price' => '557','short_description' => 'Short description for Deciduous Trees SubCategory 3 Product 1.','long_description' => 'Detailed description of Deciduous Trees SubCategory 3 Product 1.','image' => 'images/products/deciduous_trees_subcategory_3_product_1.jpg','hit_count' => '15','sales_count' => '0','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '72','name' => 'Deciduous Trees SubCategory 3 Product 2','category_id' => '5','sub_category_id' => '15','unit_id' => '1','code' => 'PRD6762B7522CDCF','model' => 'Model 2','stock_amount' => '71','regular_price' => '617','selling_price' => '678','short_description' => 'Short description for Deciduous Trees SubCategory 3 Product 2.','long_description' => 'Detailed description of Deciduous Trees SubCategory 3 Product 2.','image' => 'images/products/deciduous_trees_subcategory_3_product_2.jpg','hit_count' => '34','sales_count' => '20','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '73','name' => 'Deciduous Trees SubCategory 3 Product 3','category_id' => '5','sub_category_id' => '15','unit_id' => '1','code' => 'PRD6762B7522D4A9','model' => 'Model 3','stock_amount' => '57','regular_price' => '616','selling_price' => '436','short_description' => 'Short description for Deciduous Trees SubCategory 3 Product 3.','long_description' => 'Detailed description of Deciduous Trees SubCategory 3 Product 3.','image' => 'images/products/deciduous_trees_subcategory_3_product_3.jpg','hit_count' => '28','sales_count' => '5','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '74','name' => 'Deciduous Trees SubCategory 3 Product 4','category_id' => '5','sub_category_id' => '15','unit_id' => '1','code' => 'PRD6762B7522DB3E','model' => 'Model 4','stock_amount' => '53','regular_price' => '867','selling_price' => '558','short_description' => 'Short description for Deciduous Trees SubCategory 3 Product 4.','long_description' => 'Detailed description of Deciduous Trees SubCategory 3 Product 4.','image' => 'images/products/deciduous_trees_subcategory_3_product_4.jpg','hit_count' => '0','sales_count' => '8','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
            array('id' => '75','name' => 'Deciduous Trees SubCategory 3 Product 5','category_id' => '5','sub_category_id' => '15','unit_id' => '1','code' => 'PRD6762B7522E23A','model' => 'Model 5','stock_amount' => '33','regular_price' => '837','selling_price' => '897','short_description' => 'Short description for Deciduous Trees SubCategory 3 Product 5.','long_description' => 'Detailed description of Deciduous Trees SubCategory 3 Product 5.','image' => 'images/products/deciduous_trees_subcategory_3_product_5.jpg','hit_count' => '23','sales_count' => '0','status' => '1','created_at' => '2024-12-18 11:51:46','updated_at' => '2024-12-18 11:51:46'),
        );

        foreach ($products as $product) {
            Product::create($product);
        }

    }
}
